services:
  smtp-parser:
    
    image: sumizadocker/smtp-parser:latest
    
    ports:
      - "25:25"
    
    environment: # uncomment and change the ones you need
      IDENT: My Test SMTP Server
      # HOST: '0.0.0.0'
      # HOST_NAME: 'mail.example.com'
      # PORT: 25
      # TARGET_EMAIL: .com
      # SOURCE_EMAIL: .com
      # SPF_ALLOW_LIST: 'pass, permerror, fail, temperror, softfail, none, neutral'
      # DKIM_REJECT: True
      # DKIM_MIN_KEY: 1024
      # EMAIL_SIZE: 5048576
      # LOGGER: INFO
      # WEBHOOK_URL: https://webhookbin.net/v1/bin/4142fd66-fca8-4c36-bc04-cfa17c092a0d
      # WEBHOOK_HEADERS: '{"Test-Header":"Hi There","Test-Header2":"4"}'
      # HMAC_SECRET: SuperSecret
      # PIP_INSTALL: 'urlrequest webhookbin'
      # BUILTIN_ADDON: telnyx
      # TLS_REQUIRED: True
      # TLS_CERT_HOST: mail.example.com

    # volumes: # bring in your own cert
    #   - ~/fullchain.pem:/cert.pem
    #   - ~/privkey.pem:/key.pem

    # deploy:
    #   restart_policy:
    #     condition: any
    #     delay: 5s
    #     window: 120s

    # volumes: # if need the addon
    #   - ~/addon.py:/addon.py