services:
  smtp-parser:
    
    image: sumizadocker/smtp-parser:latest
    
    ports:
      - "25:25"
    
    environment:
      BUILTIN_ADDON: discord
      DISCORD_IDTOKEN: '109691893456346445176/Avuqw05Tmoz9pw8-Efeawf4332c-ooZR3_dy5voHRFgaregGDAgrergL8v5wphMQcMWlVD'