name: Docker Build and Push Nightly

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

  schedule:
    - cron:  '55 5 * * *'

env:
  DOCKER_USER: sumizadocker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: log into docker
      run: |
        docker logout
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USER --password-stdin

    - name: build and tag daily
      if: ${{ github.event_name == 'schedule' }}
      run: >
        docker buildx build 
        --platform linux/amd64,linux/arm64
        -f ./Dockerfile 
        -t $DOCKER_USER/${{ github.event.repository.name }}:latest 
        -t $DOCKER_USER/${{ github.event.repository.name }}:$(date --rfc-3339=date)
        .
        --push

    - name: build and tag on push or pull
      if: ${{ github.event_name != 'schedule' }}
      run: >
        docker buildx build 
        --platform linux/amd64,linux/arm64
        -f ./Dockerfile 
        -t $DOCKER_USER/${{ github.event.repository.name }}:latest
        -t $DOCKER_USER/${{ github.event.repository.name }}:${{ github.head_ref || github.ref_name }} 
        -t $DOCKER_USER/${{ github.event.repository.name }}:${{ github.sha }} 
        .
        --push

    - name: log out of docker
      run: docker logout
