name: Docker Build and Push Beta

on:
  push:
    branches: [ "beta" ]

  pull_request:
    branches: [ "beta" ]

env:
  DOCKER_USER: sumizadocker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: log into docker
      run: |
        docker logout
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USER --password-stdin

    - name: build and tag beta
      if: ${{ github.event_name != 'schedule' }}
      run: >
        docker buildx build 
        --platform linux/amd64,linux/arm64
        -f ./Dockerfile 
        -t $DOCKER_USER/${{ github.event.repository.name }}:beta
        .
        --push

    - name: log out of docker
      run: docker logout
